swagger: '2.0'
info:
  version: '1.0.0'
  title: 项目名称
  description: 项目名称 API
host: localhost
basePath: /css/api/v1/
schemes:
  - https
consumes:
  - multipart/form-data
produces:
  - application/json
tags:
#<------ tags↑

paths:
#<------ paths↑

parameters:
  Accept:
    name: Accept
    in: header
    required: true
    type: string
    default: "application/json"
    description: 默认 application/json
  Authorization:
    name: Authorization
    in: header
    required: true
    type: string
    description: 登录凭证
#<------ parameters↑

definitions:
  Res:
    title: Res
    description: 结果 0:成功 1:失败
    type: integer
  Mes:
    title: Mes
    description: 信息
    type: string
  Links:
    type: object
    properties:
      first:
        type: string
        description: 第一页链接
      last:
        type: string
        description: 最后一页链接
      prev:
        type: string
        description: 上一页链接
      next:
        type: string
        description: 下一页链接
  Meta:
    type: object
    properties:
      current_page:
        type: integer
        description: 当前页码
      form:
        type: integer
        description: from
      last_page:
        type: integer
        description: 最后页码
      links:
        type: object
        description: 分页链接
      path:
        type: string
        description: 当前访问链接
      per_page:
        type: integer
        description: 当前请求数据量
      to:
        type: integer
        description: 返回数据量
      total:
        type: integer
        description: 数据总量
#<------ definitions↑
